[workspace]

[package]
name = "battleship-methods-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
battleship-core = { path = "../../core" }
risc0-zkvm = { version = "0.19", default-features = false }

[profile.release]
lto = true
opt-level = "z"
