[workspace]

[package]
name = "battleship-methods-guest"
version = "0.1.0"
edition = "2021"

[target.riscv32im-unknown-none-elf.dependencies]
battleship-core = { path = "../../core" }
risc0-zkvm-guest = "0.10"

[profile.release]
lto = true
opt-level = "z"

[build-dependencies]
risc0-build = "0.10"
